import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--dataset', type = str, default = 'nucleus_stage1', required = True, help = 'nucleus_stage1')
parser.add_argument('--arch', type = str, default = 'unet', help = 'unet|resnet' )
parser.add_argument('--epochs', default = 90, type = int, help = 'epoch to run')
parser.add_argument('--batch_size', default = 64, type = int, help = 'batch size')
parser.add_argument('--num_workers', default = 1, type = int, help = 'num of workers')
parser.add_argument('--lr', default = 0.01, type = float, help = 'initial learning rate')
parser.add_argument('--experiments', type = str, help="dir to save train model and log")
parser.add_argument('--imageSize', default = 224, help="image size")
parser.add_argument('--use_cuda', default = True, type=bool,help ='wheater in training phase')
parser.add_argument('--resume', default = False, type = str, help = "if use previous checkpoint")
parser.add_argument('--is_train', default = True, help = "phase name")
parser.add_argument('--mode', default = "train", help = "train|test|demo")
parser.add_argument('--test_dir', default = "/home/bingzhe/dataset/kaggel/stage1_test/", help = "data root to test")
parser.add_argument("--submit_file", default = 'submit_test.csv', help = "path to save submit file")
opt = parser.parse_args()